### ISSUE TITLE
beautiful project but no license and scrapper does not work right now

### ISSUE THREAD

**Issue by bluecraank** [ilyasozkurt/automobile-models-and-specs#4]
Please fix :(

**Comment by ilyasozkurt** [comment]
I have no time.

For the license... This is a scraper and scrapes data from web and you guys asking for a license. This is unbelievable.

There is no license. This is a copied data from publicly released on autoevolution. Ask them for license.

Thank you.

**Comment by damsfx** [comment]
@ilyasozkurt I think that for those who ask for a license, it's on THIS project/repository, to be able to freely use the code in another project.

**Comment by ilyasozkurt** [comment]
You can use it whenever you want for whatever you want

**Comment by ilyasozkurt** [comment]
@bluecraank scrapper is updated by the way.
